# Generated by Django 5.0.7 on 2024-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=50, null=True, verbose_name='Enter Customer Name here')),
                ('Purchase_product', models.CharField(max_length=50, verbose_name='Enter Customer Name here')),
                ('Date', models.DateField(verbose_name='enter date here')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdctname', models.CharField(max_length=50, verbose_name='Enter Customer Name here')),
                ('price', models.IntegerField(max_length=50, null=True, verbose_name='Enter Customer Name here')),
            ],
        ),
    ]
