# Generated by Django 5.0.7 on 2024-08-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_c_name_customer_c_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Purchase_product',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Core.product', verbose_name='Enter Customer Name here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdctname',
            field=models.CharField(max_length=50, verbose_name='Enter product name Name here'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Enter product Price'),
        ),
    ]
