# Generated by Django 5.0.7 on 2024-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_customer_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Purchase_product',
            field=models.CharField(max_length=50, verbose_name='Enter Customer Name here'),
        ),
    ]
