# Generated by Django 5.0.7 on 2024-08-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_customer_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Purchase_product',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Core.product', verbose_name='Enter Customer Name here'),
        ),
    ]
