# Generated by Django 5.0.7 on 2024-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_customer_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Purchase_product',
        ),
        migrations.AddField(
            model_name='customer',
            name='Purchase_product',
            field=models.ManyToManyField(max_length=50, to='Core.product', verbose_name='Enter Customer Name here'),
        ),
    ]
