# Generated by Django 5.0.7 on 2024-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_customer_date_remove_customer_purchase_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Purchase_product',
        ),
        migrations.AddField(
            model_name='customer',
            name='Purchase_product',
            field=models.CharField(default=' ', max_length=50, verbose_name='Enter Customer Name here'),
            preserve_default=False,
        ),
    ]
