# Generated by Django 5.0.7 on 2024-08-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_remove_customer_purchase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(default='', upload_to='core/Images'),
        ),
    ]
