# Generated by Django 5.0.7 on 2024-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(default='', upload_to='Core/Images'),
        ),
    ]
