# Generated by Django 5.0.7 on 2024-08-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Purchase_product',
            field=models.CharField(max_length=50, verbose_name='Prodcust name here'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Customer Name '),
        ),
    ]
