# Generated by Django 5.0.7 on 2024-08-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_customer_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(upload_to='Core'),
        ),
    ]
