# Generated by Django 5.0.7 on 2024-08-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(default='', upload_to='CoreImages'),
        ),
    ]
