# Generated by Django 5.0.7 on 2024-08-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_customer_date_alter_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Purchase_product',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcust name here'),
        ),
    ]
