# Generated by Django 5.0.7 on 2024-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_customer_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(default='CoreImages/default_profile_pic.jpg', upload_to='CoreImages'),
        ),
    ]
