# Generated by Django 5.0.7 on 2024-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_alter_customer_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='username'),
        ),
    ]
