# Generated by Django 5.0.7 on 2024-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_acount_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='username')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='Password')),
            ],
        ),
        migrations.DeleteModel(
            name='acount',
        ),
    ]
